---
- name: Copy File
  hosts: all
  become: true
  tasks:    
    - name: example copying file with owner and permissions
      copy:
        src: /home/mancobd_sa/testfile.txt
        dest: /home/mancobd_sa/
        owner: mancobd_sa
        group: mancobd_sa
        mode: 0644
       
    
