---
- name: Copy File
  hosts: all
  become: true
  tasks:    
   - name: Copy Remote-To-Remote (from serverA to serverB)
     synchronize: src=/home/mancobd_sa/testfile.txt dest=/home/mancobd_sa/
     delegate_to: 10.169.78.134
