---
- name: Copy File
  hosts: all
  become: true
  tasks:    
    - name: example copying file with owner and permissions
      copy:
        src: "{{srcname}}"
        dest: "{{destname}}"
        owner: mancobd_sa
        group: mancobd_sa
        mode: 0644
       
    
