---
- name: Ansible Create user 
  hosts: all
  become: true
  tasks:
    - name: Add the user '{{name}}' 
      ansible.builtin.user:
        name: "{{name}}"
        comment: "{{comment}}"
        password: "{{ newpassword|password_hash('sha512') }}"
  
