
---
- name: Ansible Facts
  hosts: all
  become: true
  
  tasks: 
  - name: Show Details
    debug:
     msg: 
       - "OS NAME : {{ ansible_distribution }}"  
       - "Architecture : {{ ansible_architecture }}"
       - "Version : {{ ansible_distribution_version }}"
      
