
---
- name: Ansible Facts
  hosts: all
  become: true
  
  tasks: 
  - name: Show Details
    debug:
     msg: "OS NAME : {{ ansible_distribution }}"  
     msg: "Architecture : {{ ansible_architecture }}"
     msg: "Version : {{ ansible_distribution_version }}"
      
