
---
- name: Ansible Facts
  hosts: all
  become: true
  
  tasks:
  - name: Collect only selected facts
    ansible.builtin.setup:
      filter:
        - ansible_distribution
        - ansible_machine_id
        - ansible_*_mb
    register: details
    
  - name: Show Details
    debug:
     msg: "{{ details }}"  
      
