---
-
  hosts: ugadmin
  become: yes
  tasks:
  - name: copy falcon rpm
    copy:
      dest: /home/ugadmin/
      src: /home/ugadmin/falcon-sensor-6.22.0-11906.el7.x86_64.rpm
  - name: install new falcon
    yum:
      state: present
      name: /home/ugadmin/falcon-sensor-6.22.0-11906.el7.x86_64.rpm
  - name: setup and run falcon
    script: /home/ugadmin/setup.sh
    
