---
- name: This Installs Falcon
  hosts: 10.169.78.136
  become: true
  tasks:
  - name: Install Falcon 
    yum:
      name: falcon-sensor-6.22.0-11906.el8.x86_64
      src: falcon-sensor-6.22.0-11906.el8.x86_64
      state: started
  
    
