---
- hosts: all
  gather_facts: no
  tasks:
  - name: Password Reset For  "{{uname}}"
    user:
       name: "{{uname}}"
       update_password: always
       password: "{{ newpassword|password_hash('sha512') }}"
       password_expire_max: 90
    register: password_status
    
  - name: Show Password Details for user "{{uname}}"
    debug:
     msg: "{{ password_status }}"
