---
- hosts: all
  gather_facts: no
  vars : 
    s_expires: "{{ lookup('pipe','date +%s -d now+12months') }}"
  tasks:
  - name: Password Reset For  "{{uname}}"
    user:
       name: "{{uname}}"
       update_password: always
       password: "{{ newpassword|password_hash('sha512') }}"
       expires: "{{ s_expires }}"
    register: password_status
    
  - name: Show Password Details for user "{{uname}}"
    debug:
     msg: "{{ password_status }}"
