---
- name: Security Patch
  hosts: all
  become: true
  tasks:
  - name: Security Patch 
    yum:
      name: '*'  
      state: latest
      security: yes
    register: patch_details_status
    
  - name: Show Patch Details
    debug:
     msg: "{{ patch_details_status }}"  
      
