---
 - name: SSH KEY GEN
   hosts: all
   become: true
   tasks:
     - name: Create a 2048-bit SSH key for user '{{username}}'
       ansible.builtin.user:
         name: "{{username}}"
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
