---
- name: Check Disk Space Usage
  hosts: all
  become: true
  tasks:
          - name: Disk usage from command module
            command: "{{item}}"
            with_items:
              - df -h
              - free
            register: items         
          - debug:
                  var: items.stdout_lines
           
