---
- name: Check Disk Space Usage
  hosts: all
  become: true
  tasks:
          - name: Disk usage from command module
            shell: "{{item}}"
            with_items:
              - df -h
              - free -m
              - vmstat
            register: item         
          - debug:
              msg:      
                - "{{ item.results[0].stdout_lines }}"
                - "{{ item.results[1].stdout_lines }}"
                - "{{ item.results[2].stdout_lines }}"
                 
            
