---
- name: Check Disk Space Usage
  hosts: all
  become: true
  tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
            command: free
            register: memusage
          - debug:
                  var: memusage|space.stdout_lines
           
