---
- name: Check Disk Space Usage
  hosts: all
  become: true
  tasks:
          - name: Disk usage from command module
            shell: "{{item}}"
            with_items:
              - df -h
              - free -m
              - vmstat
            register: item         
          - debug:
              msg: "{{item.stdout_lines}}"          
            with_item
