---
- hosts: all
  become: true
  tasks:
  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: no
    register: yum_update_status
    
  - name: Show Update details
    debug:
     msg: "{{ yum_update_status }}"

  - name: Remove packages not needed anymore
    yum:
      autoremove: yes
